# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TagSelectorView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TagSelectorView
  pod 'YYKit'

  target 'TagSelectorViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TagSelectorViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
